---
title: "How Anxiety/Depression Levels Differed Between States and Regions Following COVID-19"
date: last-modified
author: "Ian Walsh & Logan Rosell"
format: 
    html:
        embed-resources: true
jupyter: python3
---

```{python}
#| echo: false
#| include: false
# Load libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy.stats import pearsonr
from sklearn.linear_model import LinearRegression
from sklearn.metrics import PredictionErrorDisplay
from scipy.stats import probplot
from statsmodels.stats.outliers_influence import variance_inflation_factor
import datetime

# Import datasets
state_data = pd.read_csv("state_data.csv")
state_data_wide = pd.read_csv("state_data_wide.csv")
# Reforming to date-time because CSV does not retain formatting
state_data['Time Period Start Date'] = pd.to_datetime(state_data['Time Period Start Date']).dt.date
state_data['Time Period End Date'] = pd.to_datetime(state_data['Time Period End Date']).dt.date

```

# Introduction

Shortly following the outbreak of COVID-19 in the United States, the CDC began to measure rates of self-reported symptoms of anxiety and depression in the United States from a survey that they sent out. They did this in part because "the spread of disease and increase in deaths during large outbreaks of transmissible diseases is often associated with fear and grief" (Vahratian, et al.). Rates of anxiety and depression symptoms were then estimated for various demographic and geographic groups to see how they changed throughout the course of the pandemic and in the aftermath. In this paper, we will explore how rates of anxiety and depression changed during this time period. More specifically, our research question is: how did anxiety and depression levels differ between states and regions following the outbreak of COVID-19 in the United States? Our null hypothesis is thus that there was no difference between rates of depression and anxiety in different regions following COVID-19, and our alternative hypothesis is that there *were* differences.

# Background

Anxiety and Depression were measured as a percentage of the population exhibiting symptoms using a Patient Health Questionnaire survey (Vahratian, Anjel). Surveys were sent via email every two weeks from 4/23/2020 to 9/20/2023. Four questions were included in the survey. During the past 7 days, respondents were asked if they had been bothered by:

1. Feeling nervous, anxious, or on edge?

2. Not being able to stop or control worrying?

3. Having little interest or pleasure in doing things?

4. Feeling down, depressed, or hopeless?

If a respondent answered yes to either of the first two questions for more than half of the previous 7 days, they were included in the population of people exhibiting symptoms of anxiety. Likewise, if an individual answered yes to either of the last two questions for more than half of the previous 7 days, they were included in the population exhibiting symptoms of depression. This paper's analysis focuses primarily on the combined anxiety and depression rate, which an individual would be included in by answering yes to any of the four survey questions for more than half of the previous 7 days. 

Focusing on regions within the United States simultaneously allowed us to narrow the scope of this analysis to 4 rather than 50 distinct subgroups and allowed us to investigate a proxy for cultural and policy variation--geographic difference's impact on symptom rates over time. Research suggests that an individual's political affiliation and socio-economic status influences their COVID-19 outcomes (Lurie, Nicole, and Sharfstein) (Suzuki, et al.). Region is associated with both political affiliation and income; thus we hypothesized it may serve as a predictor of a person's overall COVID-19 experience. Consequently, this regional difference in COVID-19 experience may predict the individual's propensity to display symptoms of anxiety and depression as the pandemic progressed.

Another possible state-to-state difference is how they responded to the pandemic itself. Some states, such as South Dakota, shut down hardly any public spaces and had very loose mask requirements, whereas states like California were very restrictive about what people were allowed to do in public regarding health and safety measures (Taylor). The difference between these state-wide approaches to public health may have left people feeling more anxious about potentially getting sick, or may have made them more depressed about not being able to go out. Either way, we believe this could be reflected in the data.

Finally, the difference in disease rates between states may have also had an impact on mental health. Texas, for example, had a mortality rate of 105.2 people per 100,000 population in 2020, while Washington saw a mortality rate of less than half of that at 36.7 per 100,000 population (“Covid-19 Mortality”). In regions where more people were dying at a higher rate from COVID, there may have been more of an emotional toll on the population as a whole.


# Methods 

During data cleaning, we included regions sorted by the US Census Definition ("Census Regions"), which breaks the United States into the South, West, Northeast, and Midwest. The data provided by the CDC included observations grouped by age, sex, ethnicity, education, state, disability status, gender identity, and sexual orientation; however, only state-level observations were preserved in our final dataset due to the focus of this project on regional differences. 

To analyze trends between major national events over the course of our dataset, we graphed anxiety and depression scores over time and visually compared movements in the data relative to those key points. 

We selected 6 key events based on the political and social impact (as judged by the authors) on the entire United States. This list is far from exhaustive.

To gauge the relationship between anxiety and depression rates over time, we performed a simple linear regression of the combined score as predicted by time period. 

# Results

## National Symptom Rate Over Time
```{python}
#| echo: false
format = '%b %d %Y'
federal_election = datetime.datetime.strptime('Nov 3 2020', format)
floyd_protests = datetime.datetime.strptime('May 25 2020', format)
covid_vaccine = datetime.datetime.strptime('Dec 11 2020', format)
roe_v_wade_overturned = datetime.datetime.strptime('Jun 24 2022', format)
us_mid_terms = datetime.datetime.strptime('Nov 8 2022', format)
covid_over = datetime.datetime.strptime('May 11 2023', format)
national_avgs = state_data.groupby(['Time Period Start Date', 'Indicator'], observed=False).agg(
    nat_means = ('Percent of Population', 'mean')
)
nat_avg_plt = sns.lineplot(national_avgs,
                            x='Time Period Start Date',
                            y='nat_means',
                            hue = 'Indicator')
plt.axvline(floyd_protests,
    color='purple',
    label='George Floyd Protests',
    linestyle='--',)
plt.axvline(federal_election,
    color='red',
    label='Federal Election',
    linestyle='-.',)
plt.axvline(covid_vaccine,
    color='black',
    label='Covid-19 Vaccine Approved',
    linestyle=':',)
plt.axvline(roe_v_wade_overturned,
    color='blue',
    label='Roe V. Wade is Overturned',
    linestyle='--',)
plt.axvline(us_mid_terms,
    color='#06754cff',
    label='Midterm Elections',
    linestyle='-.',)
plt.axvline(covid_over,
    color='orange',
    label='Covid-19 Public Health Emergency Over',
    linestyle=':',)
plt.xticks(rotation=45)
plt.title(r"$\mathbf{Figure\ 1}$: Percent of Pop with Anxiety or Depression Over Time with Major Events Included")
plt.ylabel('Percent of Population')
plt.legend(title='Key',
    loc='right',
    bbox_to_anchor=(1.9, 0.5))

fig = nat_avg_plt.get_figure()

plt.show()
```

Of the six major national events analyzed, only three clearly corresponded with a local minimum or maximum for combined anxiety and depression rates at the national level (**Fig. 1**). The US Federal Election on November 3, 2020 lined up well with the first and largest peak in our dataset for combined symptoms. Given that the federal response to the pandemic featured prominently in public discourse surrounding that election and that uncertainty is widely known to be associated with anxiety, this correspondence makes sense. Equally unsurprising is the steep and persistent drop in anxiety and depression nationwide immediately following the FDA approval of the first COVID-19 vaccines on December 11, 2020 (Park). 

The final aligned event of our triad, the overturning of Roe v. Wade (Totenberg and McCammon) on June 24, 2022, matched well with a small peak in anxiety and depression (**Fig. 1**). As compared to the previous two events, the Roe v. Wade reversal is associated with a far less prominent change in the data. This moment is immediately followed by a short decline in symptom rates, and then an even larger peak in the neighborhood of the 2022 Midterm Elections on November 8, 2022. Both of these political events occurred during a general upward movement in symptom rates nationwide, but they are difficult to isolate from one another given their proximity. 

On the theme of major political events, which are difficult to track over time, we have included the start of the George Floyd protests on May 25, 2020 (George Floyd). These protests were not a single-day event, and the Black Lives Matter movement, which expanded around this time, does not have a clear start or end date, yet was undoubtedly a major contributor to the national mood and thus likely to affect rates of anxiety and depression. We can see that May 25, 2020, lines up well with a local minimum in symptom rates, which rise sharply after that date. 

The final event included in this analysis is the Federal Government's official announcement of the end of the COVID-19 public health emergency on May 11, 2023 (End of the Federal COVID-19 Public Health Emergency). Given this announcement would appear to mark a major decrease in the burden of disease and or a change in the political mood of the nation, it is surprising to observe no major change in rates of anxiety or depression around this event (**Fig. 1**). 

```{python}
#| echo: false
#| include: false
format = '%b %d %Y'
peak_1 = datetime.datetime.strptime('Nov 3 2020', format)
trough = datetime.datetime.strptime('May 26 2021', format)
peak_2 = datetime.datetime.strptime('Sep 14 2022', format)
national_avgs = state_data.groupby(['Time Period Start Date', 'Indicator'], observed=False).agg(
    nat_means = ('Percent of Population', 'mean')
)
nat_avg_plt = sns.lineplot(national_avgs,
                            x='Time Period Start Date',
                            y='nat_means',
                            hue = 'Indicator')
nat_avg_plt.lines[0].set_linestyle("-")
nat_avg_plt.lines[1].set_linestyle("-")
nat_avg_plt.lines[2].set_linestyle("-")
plt.axvline(peak_1,
    color='black',
    label='Peak One',
    linestyle=':',)
plt.axvline(trough,
    color='black',
    label='Trough',
    linestyle=':',)
plt.axvline(peak_2,
    color='black',
    label='Peak Two',
    linestyle=':',)
plt.xticks(rotation=45)
plt.title("Percent of Pop with Anxiety or Depression Over Time ")
plt.ylabel('Percent of Population')
plt.legend(title='Key',
    loc='right',
    bbox_to_anchor=(1.9, 0.5))
plt.show()
```

## Regional Differences Over Time
```{python}
#| echo: false
min = state_data['Percent of Population'].min()
max = state_data['Percent of Population'].max()

fig = px.choropleth(
    state_data,
    locations='State Code',
    locationmode='USA-states',
    color='Percent of Population',
    facet_row='Symptoms Of',
    scope='usa',
    title= "<b>Figure 2</b>: Map of Anxiety and Depression in US States Over Time",
    hover_name='State',
    color_continuous_scale='amp',
    animation_frame='Time Period Start Date',
    range_color=[min,max],
    height = 700
)

fig.show()
```

```{python}
#| echo: false
regional_diff = sns.lineplot(state_data[state_data["Indicator"] == "Symptoms of Anxiety Disorder or Depressive Disorder"],
    x="Time Period Start Date",
    y="Percent of Population",
    hue="Region",
    errorbar=None)
regional_diff.set(title=r"$\mathbf{Figure\ 3}$: Combined Symptoms Over Time by Region")
plt.xticks(rotation=45)
plt.show()
```

Though this paper primarily focuses on the percentage of the population experiencing either anxiety or depression, it is worth noting that across the entire US, at no time in our dataset did rates of depression symptoms exceed those of anxiety (**Fig. 2**). 

Looking at the combined symptom rates around the first peak (11/11/2020 in **Fig. 3**), we observe generally darker shading (**Fig. 2**), indicating higher symptom rates, in the lower half of the contiguous United States, with New Mexico the worst state at 49.7% of the population exhibiting anxiety or depression symptoms. Florida is a notable southern standout in the opposite direction, with only 41.3% of the population showing symptoms. 

Combined symptom rates during the first major trough in the data (**Fig. 3**)--May 5, 2022--reveal an even more obvious divide between the Northern United States, specifically the Midwest, with lower scores than the Southern states, especially those around Louisiana. 

While there is a persistent trend between North and South, it should be noted that there is a large variation in states regardless of latitude between each two-week time period (**Fig. 2**). 

Certain regions are consistently higher than others throughout most of the time period we looked at (**Fig. 3**). Specifically, the Midwest and Northeast regions of the United States appear to consistently have lower rates of anxiety or depression, whereas the South and West have much higher rates. For example, at the highest peak in the data (around December 2020), the West had an anxiety or depression rate of over 43, but in the Midwest, that rate was just over 40 (**Fig. 3**).

## Linear Regression

In order to better analyze this data, we ran a linear regression model with the percent of the population with symptoms of either depression or anxiety as our response variable, and time period and regions as our explanatory variables. For this regression, one observation was the average population with symptoms of anxiety or depression per time period per state, which left us with 3,162 total observations. Dummy variables were created for each region except for the Midwest. This means that if all other regions are 0, that observation represents the Midwest, and thus it does not have it's own coefficient (but is instead factored into the model intercept). Our results are as follows:

```{python}
#| echo: false
x_data = state_data_wide[['Time Period',
        'Region_South',
        'Region_West',
        'Region_Northeast']]
y_data = state_data_wide[['Perc of Pop with Symptoms of Either']]

symptoms_over_time_by_region = LinearRegression().fit(x_data,y_data)
score = symptoms_over_time_by_region.score(x_data, y_data)
predict = symptoms_over_time_by_region.predict(x_data)

print('Model Intercept:', round(symptoms_over_time_by_region.intercept_[0], 3))
print('\nModel Coefficients: ')
for name, coef in zip(x_data.columns, symptoms_over_time_by_region.coef_.flatten()):
    print(f'{name} = {coef:.3f}')
print('\nModel R-Squared: ', round(symptoms_over_time_by_region.score(x_data, y_data), 3))
```

```{python}
#| echo: false
linear_plot = sns.lmplot(state_data_wide,
    x='Time Period',
    y='Perc of Pop with Symptoms of Either',
    col= "Region",
    col_wrap = 2,
    line_kws={'color': 'red'})

fig = linear_plot.fig

fig.suptitle(r"$\mathbf{Figure\ 4}$: Regression of Percent of Symptoms of Depression or Anxiety Over Time, by Region", fontsize=14)

plt.tight_layout()
plt.show()
```

The findings of this linear regression model are consistent with our earlier observations of the regional differences over time (**Fig. 3**). Overall, there is a downward trend for every region, but the regions had different model intercepts (**Fig. 4**). For example, the Midwest had a model intercept of 34.755, but the South had an intercept that was 3.710 higher at 38.465. As is evident in our low R-Squared and the graphical representation of the data (**Fig. 4**), however, the data does not appear very linear. So, a linear regression model is likely not the best fit for this data. Below, we will explore checks for the assumptions of a linear regression model: linearity, independent observations, normally-distributed residuals, and equal variance for all explanatory variables.

### Checks for Assumptions of a Linear Regression Model

```{python}
#| echo: false
display = PredictionErrorDisplay(y_true = y_data, y_pred = predict)
display.plot()
plt.title(r"$\mathbf{Figure\ 5}$: Residuals Plot of Linear Regression Model")
plt.show()

# Does not meet criteria for linearity or equal variance (L, E)
```

The residual plot can be used to measure the linearity and equal variance assumptions of a linear model. In our case, the data does not appear to have homoscedasticity, and there are clear patterns that emerge in the residuals (**Fig. 5**). Thus, it does not appear our model meets the criteria for linearity or equal variance.

```{python}
#| echo: false
residuals = y_data - predict
residuals = np.ravel(residuals)

probplot(residuals, dist = 'norm', plot = plt)
plt.title(r"$\mathbf{Figure\ 6}$: Q-Q Plot of Linear Regression Model")
plt.show()

# Data looks fairly normally distributed (N)
```

We also generated a Q-Q plot to analyze the distribution of the residuals in our model. For this test, it does appear that our residuals are fairly normally distributed, with only slight deviations on the ends (**Fig. 6**). It does appear that this model meets the criteria for normally distributed residuals. 

Finally, we looked at the Variance Inflation Factor (VIF) for our explanatory variables. The results are as follows:
```{python}
#| echo: false
X = state_data_wide[['Time Period',
    'Region_South',
    'Region_West',
    'Region_Northeast']].copy()

X = X.astype(float)

X.insert(0, 'const', 1.0)

X_array = X.values

for i, col in enumerate(X.columns):
    if i == 0:
        continue
    vif = variance_inflation_factor(X_array, exog_idx=i)
    print(col, "VIF =", round(vif, 3))
``` 

Because all of our VIF values are quite low (far less than 5), there does not appear to be evidence of multicollinearity in our model.

# Conclusion

In conclusion, we can reject our null hypothesis that there was no difference between rates of depression and anxiety in different regions following COVID-19, and accept our alternative hypothesis that there were differences in the rates. Specifically, we find that the Midwest had the lowest rate of anxiety or depression during and immediately following the pandemic. The Northeast had relatively low rates as well, whereas the West and South regions had the highest rates, with the South being the highest overall.

There are some additional findings that we observed during our analysis. There was an apparent spike in anxiety and depression rates following the initial outbreak of COVID that continued throughout 2020, but that began to fall in 2021 to a relatively steady rate (with minor fluctuations). Also, we noticed throughout the data (such as in **Fig. 1**) that anxiety rates overall tended to be much higher than depression.

Some caveats to our findings include the fact that, as mentioned above, our linear regression model was not a great fit. In addition to not meeting the assumptions of linearity or equal variance of residuals, the model only explained about 19% of the variation in our response variable. Another caveat is that while there were shifts in the data that visually appear to have been correlated with major events (**Fig. 1**), we have no conclusive evidence to support the causality of these events. Thus, we can only speculate that these events may have had an impact on the changes in rates that we saw.

# References

1. *Census Regions and Divisions of the United States*, U.S. Census Bureau, www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf. Accessed 2 Dec. 2025. 
2. “Covid-19 Mortality.” *Centers for Disease Control and Prevention*, 20 Aug. 2025, www.cdc.gov/nchs/state-stats/deaths/covid19.html. 
3. “End of the Federal COVID-19 Public Health Emergency (PHE) Declaration.” *Centers for Disease Control and Prevention*, 12 Sept. 2023, archive.cdc.gov/www_cdc_gov/coronavirus/2019-ncov/your-health/end-of-phe.html. 
4. “George Floyd: Timeline of Black Deaths and Protests.” *BBC News*, BBC, 22 Apr. 2021, www.bbc.com/news/world-us-canada-52905408. 
5. Hayward, Ed. “Covid-19’s Toll on Mental Health.” *Boston College*, Apr. 2021, www.bc.edu/bc-web/bcnews/campus-community/faculty/anxiety-and-stress-spike-during-pandemic.html. 
6. Lurie, Nicole, and Joshua M Sharfstein. “State-to-state differences in US covid-19 outcomes: Searching for explanations.” The Lancet, vol. 401, no. 10385, 22 Apr. 2023, pp. 1314–1315, https://doi.org/10.1016/s0140-6736(23)00726-2. 
7. Park, Alice. “The First Authorized COVID-19 Vaccine in the U.S. Has Arrived.” *Time*, 11 Dec. 2020, time.com/5920134/first-authorized-covid-19-vaccine-us/.
8. Suzuki, Sara et al. “Trajectories of sociopolitical stress during the 2020 United States presidential election season: Associations with psychological well-being, civic action, and social identities.” *Comprehensive psychoneuroendocrinology* vol. 16 100218. 31 Oct. 2023, doi:10.1016/j.cpnec.2023.100218 
9. Taylor, Mia. “Which States with the Most and Fewest Coronavirus Restrictions.” *Cheapism*, 17 Sept. 2020, www.cheapism.com/coronavirus-restrictions/. 
10. Totenberg, Nina, and Sarah McCammon. “Supreme Court Overturns Roe v. Wade, Ending Right to Abortion Upheld for Decades.” *NPR*, 24 June 2022, www.npr.org/2022/06/24/1102305878/supreme-court-abortion-roe-v-wade-decision-overturn. 
11. Vahratian, Anjel, et al. “Symptoms of Anxiety or Depressive Disorder and Use of Mental Health Care among Adults during the COVID-19 Pandemic - United States, August 2020–February 2021.” *Centers for Disease Control and Prevention*, 2 Apr. 2021, www.cdc.gov/mmwr/volumes/70/wr/mm7013e2.htm. 